export const FETCH_GROUP = "FETCH_GROUP";
export const FETCH_SINGLE = "FETCH_SINGLE";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_SINGLE_USER = "FETCH_SINGLE_USER";
export const SET_PAGE = "SET_PAGE";
export const FETCH_POSITIONS = "FETCH_POSITIONS";
export const FETCH_SINGLE_POSITION = "FETCH_SINGLE_POSITION";